<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.sease.evaluation</groupId>
    <artifactId>my-rre-evaluation</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>RRE - Evaluation Project</name>
    <properties>
        <rre.version>1.2-SNAPSHOT</rre.version>
    </properties>
    <build>
        <plugins>
            <plugin>
            <groupId>io.sease</groupId>
            <artifactId>rre-maven-external-elasticsearch-plugin</artifactId>
            <version>7.5.0</version>
            <configuration>
                <elasticsearchHosts>localhost:9200</elasticsearchHosts>

                <!-- if you keep everything directly in src/etc -->
                <configurations-folder>${basedir}/src/etc</configurations-folder>

                <ratings-folder>${basedir}/src/etc</ratings-folder>
                <templates-folder>${basedir}/src/etc/templates</templates-folder>

                <fields>title,description</fields>
            </configuration>
            </plugin>
        </plugins>
    </build>
</project>
