[project]
name = "Dataset-Generator"
version = "0.1.0"
description = "Dataset Generator - A tool to generate an evaluation dataset given a collection of document"
readme = "README.md"
licence = {file = "LICENSE.md"}
authors = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.4",
    "langchain-core>=0.3.68",
    "langchain-openai>=0.3.27",
    "langchain-google-genai>=2.1.7",
]

[project.scripts]
dataset-generator = "dataset_generator.main:main"

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
